X(LIT_TYPE, INTERPRETER, ERROR, "unimplemented lit operator '%s'")
X(UNARY_TYPE, INTERPRETER, ERROR, "unimplemented unary operator '%s'")
X(UNARY_MINUS_TYPE, INTERPRETER, ERROR,
  "unary minus operator requires a numeral expression")
X(BINARY_TYPE, INTERPRETER, ERROR, "unimplemented binary operator '%s'")
X(BINARY_MINUS_TYPE, INTERPRETER, ERROR,
  "binary minus operator requires numeral expressions")
X(BINARY_SLASH_TYPE, INTERPRETER, ERROR,
  "binary slash operator requires numeral expressions")
X(BINARY_STAR_TYPE, INTERPRETER, ERROR,
  "binary star operator requires numeral expressions")
X(BINARY_PLUS_TYPE, INTERPRETER, ERROR,
  "binary plus operator requires numeral expressions")
X(BINARY_GREATER_TYPE, INTERPRETER, ERROR,
  "binary greater than operator requires numeral expressions")
X(BINARY_GREATER_EQUAL_TYPE, INTERPRETER, ERROR,
  "binary greater than or equal operator requires numeral expressions")
X(BINARY_LESS_TYPE, INTERPRETER, ERROR,
  "binary less than operator requires numeral expressions")
X(BINARY_LESS_EQUAL_TYPE, INTERPRETER, ERROR,
  "binary less than or equal operator requires numeral expressions")
X(DIV_ZERO, INTERPRETER, ERROR, "division by zero")
